title: Miles' Blog
description: 天涯何處無幹話，何必要講實務話
avatar: https://avatars1.githubusercontent.com/u/1258752
url: https://mileschou.github.io/
theme: jekyll-theme-cayman

defaults:
  - scope:
      type: ironman
    values:
      layout: ironman
      permalink: /:collection/:path
  - scope:
      path: _ironman/analyze-laravel
    values:
      series: analyze-laravel
      description: Laravel 原始碼分析
      topic_tags: [Laravel]
  - scope:
      path: _ironman/decompose-wheels
    values:
      series: decompose-wheels
      description: 輪子們，聽口令，大部分解開始！
  - scope:
      path: _ironman/golang-started
    values:
      series: golang-started
      description: 從無到有，使用 Go 開發應用程式
  - scope:
      path: _ironman/intro-of-ci
    values:
      series: intro-of-ci
      description: CI 從入門到入坑
  - scope:
      path: _ironman/refactoring
    values:
      series: refactoring
      description: 看到 code 寫成這樣我也是醉了，不如試試重構？
  - scope:
      path: _ironman/authentication
    values:
      series: authentication
      description: 我是誰？我在哪？

collections:
  ironman:
    output: true
  series:
    output: true

nav:
  - title: 部落格
    link: /
  - title: 鐵人賽
    link: /ironman
  - title: 系列文
    link: /series

# Use the Pagination plugin, see https://github.com/jekyll/jekyll-paginate
paginate: 5

# Use the Archives plugin, see https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive-category
    tag: archive-category
    year: archive-year

plugins:
  - jekyll-archives
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea
